name: “Rebuild search.json on articles update”

on:
  push:
    # Only run when files under `articles/` change
    paths:
      - 'articles/**'
      - 'search.json'           # optional: rebuild when manifest itself changes :contentReference[oaicite:0]{index=0}

jobs:
  build_search_index:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab the repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # get full history, so we can commit back :contentReference[oaicite:1]{index=1}

      # 2. Set up Node.js (so our script can run)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install deps (if any)
      - name: Install dependencies
        run: npm ci

      # 4. Build the new search.json
      - name: Build search.json
        run: node scripts/build-search-json.js

      # 5. Commit & push the updated file
      - name: Commit updated search.json
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'chore: update search.json index'
          add: 'search.json'
