name: Minify Assets

on:
  push:
    branches:
      - master

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Parcel CSS CLI
        run: npm install --no-save @parcel/css-cli

      - name: Compile & Minify with Nesting
        run: |
          npx parcel-css \
            --minify \
            --nesting \
            assets/styles/style.css:assets/styles/style.css \
            assets/styles/index.css:assets/styles/index.css \
            assets/styles/search.css:assets/styles/search.css \
            assets/styles/about-us.css:assets/styles/about-us.css


