name: Minify Assets

on:
  push:
    branches:
      - master

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Minify HTML, CSS & JS
        uses: docker://devatherock/minify-js:3.1.0
        with:
          directory: 'assets'           
          add_suffix: false             
          
          inclusions: |-
            .*\.css$
            .*\.js$

