name: Minify CSS

on:
  push:
    branches:
      - master

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Minify all CSS with parcel-css
        run: |
          echo "🔍 Found these CSS files:"
          ls assets/styles/*.css || exit 1

          for file in assets/styles/*.css; do
            echo "⏳ Minifying $file…"
            npx parcel-css \
              --minify \
              --nesting \
              "$file" \
              --output-path "$file"
            echo "✅ Done: $file"
          done
