name: Minify Assets

on:
  push:
    branches:
      - master

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Auto Minify JS & CSS
        uses: nizarmah/auto-minify@v3
        with:
          paths: |
            assets/styles
            assets/scripts
          recursive: true
          overwrite: true