name: Minify CSS with PostCSS CLI

on:
  push:
    branches:
      - master

jobs:
  minify-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Minify all CSS with PostCSS
        run: |
          echo "🔍 Found these CSS files:"
          ls assets/styles/*.css

          for file in assets/styles/*.css; do
            echo "⏳ Minifying $file…"
            npx -p postcss-cli -p postcss-preset-env -p postcss-nested -p cssnano postcss "$file" \
              --use postcss-preset-env postcss-nested cssnano \
              --replace --no-map
            echo "✅ Done: $file"
          done

      - name: Install Terser
        run: npm install terser --no-save

      - name: Minify JS modules
        run: |
          echo "🔍 Found JS files:"
          ls assets/scripts/*.mjs

          for file in assets/scripts/*.mjs; do
            echo "⏳ Minifying $file…"
            npx terser "$file" \
                --compress \
                --mangle \
                --output "$file"
            echo "✅ Done: $file"
          done

      - name: Commit minified assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/styles/*.css assets/scripts/*.mjs
          git commit -m "chore: minified CSS & JS in CI" || echo "No changes to commit"
          git pull --rebase
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
