name: update-search-index

on:
  push:
    paths:
      - 'articles/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update search index
        run: node scripts/update-search-index.mjs

      - name: Update author pages
        run: node scripts/update-author-pages.mjs

      - name: Update latest posts
        run: node scripts/update-latest-posts.mjs

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/search.json authors/*.html index.html
          git commit -m "chore: update search index, author pages, and latest posts" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
